### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Sirz3chs**
Update extension dependencies:
- quarkus: 2.14.3.Final
- jooq: 3.16.11 (last version compatible JDK11)

Duplicate:
- https://github.com/quarkiverse/quarkus-jooq/pull/105
- https://github.com/quarkiverse/quarkus-jooq/pull/102
- https://github.com/quarkiverse/quarkus-jooq/pull/100

Fixes: 
- https://github.com/quarkiverse/quarkus-jooq/issues/89

### CODE REVIEW

**Comment by jdussouillez** [comment]
@gastaldi Thanks for the merge! Do you have any ETA for a release?

That would be the nicest Christmas present you could get us! :smile:

**Comment by gastaldi** [comment]
@jdussouillez that's up to @angrymango, as he is the lead maintainer of this extension :)

**Comment by snasib** [comment]
@angrymango can you please release this?

**Comment by ranjanashish** [comment]
@gastaldi Based on @angrymango's GitHub activity, it looks like he hasn't been active since May 2022. Can someone else please release a new version of this extension?

**Comment by gastaldi** [comment]
@ranjanashish @snasib @jdussouillez I released 0.4.0. 
Because the lead maintainer isn't too active, are any of you guys interested in becoming maintainers of this extension?

**Comment by gastaldi** [comment]
@all-contributors add @Sirz3chs for code and maintenance

**Comment by ranjanashish** [comment]
@gastaldi Yes, I would be happy to help maintain this extension.

**Pull request merged**
