### PR TITLE
Update jOOQ version

### PR DESCRIPTION
**Pull request by glandais**
Fixes :
 - https://github.com/jOOQ/jOOQ/milestone/205
 - https://github.com/jOOQ/jOOQ/milestone/203

### CODE REVIEW

**Comment by jdussouillez** [comment]
We are currently waiting for this as jOOQ < 3.15.2 contains some bugs.

Actually we could use jOOQ v3.15.4, the latest version today.

**Comment by earthride** [comment]
v3.15.5 is out, but there doesn't seem to be any activity in this repo. I suppose I'll look towards micronaut as an alternative, which has first class JOOQ support.

**Comment by gsmet** [comment]
We had an issue with the Dependabot setup in this repository. It is now fixed. I will close this PR and release a new version with the updates.

**Comment by gsmet** [comment]
0.0.3 is available on Maven Central with all the upgrades done.

**Pull request closed without merging**
